name: "PR Close"
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  merge_pr:
    name: "PR Merged"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.ADMIN_NAME }}"
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major-bump')
        run: npm version major
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor-bump')
        run: npm version minor
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch-bump')
        run: npm version patch
      - name: Git push version bump
        run: git push origin main --follow-tags --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
