name: "PR Open"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  add_comment:
    name: "Add Comment"
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Please set a versioning label of either `major-bump`, `minor-bump`, or `patch-bump` to the pull request.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
